(function(){
  var labels={activity_competition:"活动竞赛",course_selection:"选课通知",exchange:"交流交换",fees:"费用缴纳",holiday:"假期安排",library:"图书馆",registration:"报到注册",safety:"安全提示",transportation:"校园交通",other:"其他"};
  var list=document.querySelector("[data-resource-list]");var detail=document.querySelector("[data-resource-detail]");var categories=document.querySelector("[data-categories]");var search=document.querySelector("[data-search]");var initialParams=new URLSearchParams(window.location.search);var activeCategory=initialParams.get("category")||"";var timer;search.value=initialParams.get("q")||"";
  function api(url){return fetch(url).then(function(r){if(!r.ok)throw new Error();return r.json()})}
  function button(label,value,count){var b=document.createElement("button");b.type="button";b.textContent=label+(typeof count==="number"?" "+count:"");b.dataset.category=value;if(value===activeCategory)b.classList.add("active");b.addEventListener("click",function(){activeCategory=value;categories.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");load()});return b}
  function renderCategories(map,total){categories.textContent="";categories.appendChild(button("全部","",total));Object.keys(map).sort().forEach(function(key){categories.appendChild(button(labels[key]||key,key,map[key]))})}
  function showDetail(id,card){api("/api/resources/"+id).then(function(data){var r=data.resource;detail.textContent="";var box=document.createElement("div");box.className="detail-content";var top=document.createElement("div");top.className="detail-top";var category=document.createElement("span");category.textContent=labels[r.category]||r.category;var date=document.createElement("span");date.textContent=r.publish_date||"日期未注明";top.append(category,date);var title=document.createElement("h2");title.textContent=r.title;var source=document.createElement("p");source.className="detail-source";source.textContent="来源："+(r.department||"学校官网");var body=document.createElement("div");body.className="detail-body";body.textContent=r.content;var link=document.createElement("a");link.className="original-link";link.href=r.url;link.target="_blank";link.rel="noopener noreferrer";link.textContent="查看学校官网原文";box.append(top,title,source,body,link);detail.appendChild(box);detail.classList.add("open");document.querySelectorAll(".notice-card").forEach(function(x){x.classList.remove("active")});if(card)card.classList.add("active")})}
  function load(){var params=new URLSearchParams();if(activeCategory)params.set("category",activeCategory);if(search.value.trim())params.set("q",search.value.trim());list.innerHTML='<p class="library-state">正在加载资料……</p>';api("/api/resources?"+params).then(function(data){document.querySelector("[data-total]").textContent=data.categories?Object.values(data.categories).reduce(function(a,b){return a+b},0)+" 条资料":"";document.querySelector("[data-result-count]").textContent=data.count+" 条";if(!categories.children.length)renderCategories(data.categories,data.count);list.textContent="";if(!data.resources.length){list.innerHTML='<p class="library-state">没有找到相关资料，换个关键词试试。</p>';return}data.resources.forEach(function(r){var card=document.createElement("button");card.type="button";card.className="notice-card";var meta=document.createElement("div");meta.className="notice-meta";var category=document.createElement("span");category.className="notice-category";category.textContent=labels[r.category]||r.category;var date=document.createElement("span");date.textContent=r.publish_date||"日期未注明";meta.append(category,date);var title=document.createElement("h2");title.textContent=r.title;var summary=document.createElement("p");summary.textContent=r.summary;card.append(meta,title,summary);card.addEventListener("click",function(){showDetail(r.id,card)});list.appendChild(card)})}).catch(function(){list.innerHTML='<p class="library-state">资料暂时无法读取，请稍后再试。</p>'})}
  search.addEventListener("input",function(){clearTimeout(timer);timer=setTimeout(load,280)});detail.addEventListener("click",function(e){if(window.innerWidth<=840&&e.target===detail.firstElementChild)detail.classList.remove("open")});load();
})();
