(function(){
  var labels={activity_competition:"活动竞赛",course_selection:"选课通知",exchange:"交流交换",fees:"费用缴纳",holiday:"假期安排",library:"图书馆",registration:"报到注册",safety:"安全提示",transportation:"校园交通",other:"其他"};
  var input=document.querySelector("[data-file-input]");var importButton=document.querySelector("[data-import]");var status=document.querySelector("[data-upload-status]");var list=document.querySelector("[data-admin-resources]");var template=document.querySelector("#admin-resource-template");
  function request(url,options){return fetch(url,options).then(function(r){return r.json().catch(function(){return{}}).then(function(data){if(!r.ok)throw new Error(data.message||"请求失败");return data})})}
  function load(){list.innerHTML='<p class="loading-state">正在读取资料……</p>';request("/api/resources").then(function(data){document.querySelector("[data-resource-count]").textContent=data.count+" 条";list.textContent="";if(!data.resources.length){list.innerHTML='<p class="empty-state">还没有资料，请先上传 JSON 文件。</p>';return}data.resources.forEach(function(r){var item=template.content.cloneNode(true);item.querySelector("[data-category]").textContent=labels[r.category]||r.category;item.querySelector("[data-date]").textContent=r.publish_date||"日期未注明";item.querySelector("[data-title]").textContent=r.title;item.querySelector("[data-source]").href=r.url;item.querySelector("[data-delete]").addEventListener("click",function(){if(!confirm("确定删除这条资料吗？"))return;request("/api/admin/resources/"+r.id,{method:"DELETE"}).then(load)});list.appendChild(item)})}).catch(function(){list.innerHTML='<p class="loading-state error-state">无法读取资料，请确认 SSH 隧道仍在运行。</p>'})}
  input.addEventListener("change",function(){var files=Array.from(input.files);importButton.disabled=!files.length;status.className="upload-status";status.textContent=files.length?"已选择 "+files.length+" 个文件":"尚未选择文件"});
  importButton.addEventListener("click",async function(){var files=Array.from(input.files);if(!files.length)return;importButton.disabled=true;var totals={inserted:0,updated:0,skipped:0};try{for(var file of files){if(file.size>2*1024*1024)throw new Error(file.name+" 超过 2MB");var items=JSON.parse(await file.text());if(!Array.isArray(items))throw new Error(file.name+" 不是 JSON 数组");var result=await request("/api/admin/resources/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:items})});totals.inserted+=result.inserted;totals.updated+=result.updated;totals.skipped+=result.skipped}status.className="upload-status success";status.textContent="导入完成：新增 "+totals.inserted+"，更新 "+totals.updated+"，跳过 "+totals.skipped;input.value="";load()}catch(error){status.className="upload-status error";status.textContent=error.message||"导入失败"}finally{importButton.disabled=!input.files.length}});
  document.querySelector("[data-refresh]").addEventListener("click",load);load();
})();
